# Generated by Django 2.0.6 on 2018-06-29 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grin',
            fields=[
                ('id', models.UUIDField(default='2fUm6UzjaguTbc4eFoo38W', editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='last_edited',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default='2fUm6UzjaguTbc4eFoo38W', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reason',
            name='id',
            field=models.UUIDField(default='2fUm6UzjaguTbc4eFoo38W', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.UUIDField(default='2fUm6UzjaguTbc4eFoo38W', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='grin',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grins', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='grin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grins', to=settings.AUTH_USER_MODEL),
        ),
    ]
